version: "3.6"

services:
  import:
    build: ./lcp-import/
    depends_on:
      - postgres
      - es
      - cm
    environment:
      SIMPLIFIED_PRODUCTION_DATABASE: postgres://${CM_DATABASE_USERNAME}:${CM_DATABASE_PASSWORD}@${CM_DATABASE_HOST}:${CM_DATABASE_PORT}/${CM_DATABASE_DATABASE}
    volumes:
      - ./lcp-collection/collection:/var/tmp/lcp-collection
      - intermediate-repository:/${CM_REPOSITORY}
    networks:
      - back
